CREATE TABLE VARIABLE_SETS ( 
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	NAME VARCHAR(500) NOT NULL, 
	UPPERCASE_NAME VARCHAR(500) NOT NULL, 
	DESCRIPTION CLOB(1048576) NOT NULL, 
	VARIABLES CLOB(1048576) NOT NULL
);
					
ALTER TABLE VARIABLE_SETS 
ADD CONSTRAINT VS_PK PRIMARY KEY (ID);

ALTER TABLE VARIABLE_SETS 
ADD CONSTRAINT VS_U_NAME UNIQUE (NAME);

ALTER TABLE VARIABLE_SETS 
ADD CONSTRAINT VS_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);