CREATE TABLE VARIABLE_SET_LISTS ( 
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	NAME VARCHAR(500) NOT NULL, 
	UPPERCASE_NAME VARCHAR(500) NOT NULL, 
	DESCRIPTION CLOB(1048576)
);
					
ALTER TABLE VARIABLE_SET_LISTS 
ADD CONSTRAINT VSL_PK PRIMARY KEY (ID);

ALTER TABLE VARIABLE_SET_LISTS 
ADD CONSTRAINT VSL_U_NAME UNIQUE (NAME);

ALTER TABLE VARIABLE_SET_LISTS 
ADD CONSTRAINT VSL_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);