CREATE TABLE METRIC_LAST_SEEN ( 
	METRIC_KEY_SHA1 VARCHAR(50) NOT NULL,  
	METRIC_KEY CLOB(1048576) NOT NULL,  
	LAST_MODIFIED TIMESTAMP NOT NULL  
);

ALTER TABLE METRIC_LAST_SEEN 
ADD CONSTRAINT MLS_PK PRIMARY KEY (METRIC_KEY_SHA1);