CREATE TABLE GAUGES (
	BUCKET_SHA1 VARCHAR(50) NOT NULL, 
	BUCKET CLOB(1048576) NOT NULL, 
	METRIC_VALUE DECIMAL(31,7) NOT NULL,
	LAST_MODIFIED TIMESTAMP NOT NULL 
);

ALTER TABLE GAUGES 
ADD CONSTRAINT G_PK PRIMARY KEY (BUCKET_SHA1);