CREATE TABLE METRIC_GROUPS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	NAME VARCHAR(500) NOT NULL, 
	UPPERCASE_NAME VARCHAR(500) NOT NULL, 
	DESCRIPTION CLOB(1048576) NOT NULL
);

ALTER TABLE METRIC_GROUPS 
ADD CONSTRAINT MG_PK PRIMARY KEY (ID);

ALTER TABLE METRIC_GROUPS 
ADD CONSTRAINT MG_U_NAME UNIQUE (NAME);

ALTER TABLE METRIC_GROUPS 
ADD CONSTRAINT MG_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);