CREATE TABLE NOTIFICATION_GROUPS ( 
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),  
	NAME VARCHAR(500) NOT NULL,  
	UPPERCASE_NAME VARCHAR(500) NOT NULL,  
	EMAIL_ADDRESSES CLOB(65535) NOT NULL 
);

ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_PK PRIMARY KEY (ID);

ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_U_NAME UNIQUE (NAME);

ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);