CREATE TABLE SUSPENSIONS ( 
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),  
	NAME VARCHAR(500) NOT NULL,  
	UPPERCASE_NAME VARCHAR(500) NOT NULL,  
	DESCRIPTION CLOB(1048576) NOT NULL,  
	IS_ENABLED BOOLEAN NOT NULL,  
	SUSPEND_BY INTEGER NOT NULL,  
	ALERT_ID INTEGER, 
	METRIC_GROUP_TAGS_INCLUSIVE CLOB(1048576),  
	METRIC_GROUP_TAGS_EXCLUSIVE CLOB(1048576),  
	METRIC_SUSPENSION_REGEXES CLOB(1048576), 
	IS_ONE_TIME BOOLEAN NOT NULL,  
	IS_SUSPEND_NOTIFICATION_ONLY BOOLEAN NOT NULL,  
	IS_RECUR_SUNDAY BOOLEAN NOT NULL,  
	IS_RECUR_MONDAY BOOLEAN NOT NULL,  
	IS_RECUR_TUESDAY BOOLEAN NOT NULL,  
	IS_RECUR_WEDNESDAY BOOLEAN NOT NULL,  
	IS_RECUR_THURSDAY BOOLEAN NOT NULL,  
	IS_RECUR_FRIDAY BOOLEAN NOT NULL,  
	IS_RECUR_SATURDAY BOOLEAN NOT NULL, 
	START_DATE TIMESTAMP NOT NULL,  
	START_TIME TIMESTAMP NOT NULL, 
	DURATION BIGINT NOT NULL,  
	DURATION_TIME_UNIT INTEGER NOT NULL,  
	DELETE_AT_TIMESTAMP TIMESTAMP  
);

ALTER TABLE SUSPENSIONS 
ADD CONSTRAINT AS_PK PRIMARY KEY (ID);

ALTER TABLE SUSPENSIONS 
ADD CONSTRAINT AS_U_NAME UNIQUE (NAME);

ALTER TABLE SUSPENSIONS 
ADD CONSTRAINT AS_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);

CREATE INDEX AS_SUSPEND_BY ON SUSPENSIONS(SUSPEND_BY);

CREATE INDEX AS_DELETE_AT_TIMESTAMP ON SUSPENSIONS(DELETE_AT_TIMESTAMP);

ALTER TABLE SUSPENSIONS 
ADD CONSTRAINT AS_AID_FK FOREIGN KEY (ALERT_ID) REFERENCES ALERTS(ID);