CREATE TABLE OUTPUT_BLACKLIST (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),  
	METRIC_GROUP_ID INTEGER
);

ALTER TABLE OUTPUT_BLACKLIST 
ADD CONSTRAINT OB_PK PRIMARY KEY (ID);

ALTER TABLE OUTPUT_BLACKLIST 
ADD CONSTRAINT OB_MGID_FK FOREIGN KEY (METRIC_GROUP_ID) REFERENCES METRIC_GROUPS(ID);