ALTER TABLE NOTIFICATION_GROUPS ADD COLUMN PAGERDUTY_SERVICE_ID INTEGER;

ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_PDSID_FK FOREIGN KEY (PAGERDUTY_SERVICE_ID) REFERENCES PAGERDUTY_SERVICES(ID);