ALTER TABLE ALERTS ADD COLUMN IS_TEMPLATE BOOLEAN;
CREATE INDEX A_IT ON ALERTS(IS_TEMPLATE);
UPDATE ALERTS SET IS_TEMPLATE = FALSE WHERE IS_TEMPLATE IS NULL;
ALTER TABLE ALERTS ALTER COLUMN IS_TEMPLATE NOT NULL;

ALTER TABLE ALERTS ADD COLUMN IS_TEMPLATE_DERIVED BOOLEAN;
CREATE INDEX A_ITD ON ALERTS(IS_TEMPLATE_DERIVED);
UPDATE ALERTS SET IS_TEMPLATE_DERIVED = FALSE WHERE IS_TEMPLATE_DERIVED IS NULL;
ALTER TABLE ALERTS ALTER COLUMN IS_TEMPLATE_DERIVED NOT NULL;