CREATE TABLE VARIABLE_SETS ( 
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	NAME VARCHAR(500) NOT NULL, 
	UPPERCASE_NAME VARCHAR(500) NOT NULL, 
	DESCRIPTION MEDIUMTEXT NOT NULL, 
	VARIABLES MEDIUMTEXT NOT NULL
);

ALTER TABLE VARIABLE_SETS 
ADD CONSTRAINT VS_U_NAME UNIQUE (NAME);

ALTER TABLE VARIABLE_SETS 
ADD CONSTRAINT VS_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);