CREATE TABLE VARIABLE_SET_LISTS ( 
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	NAME VARCHAR(500) NOT NULL, 
	UPPERCASE_NAME VARCHAR(500) NOT NULL, 
	DESCRIPTION MEDIUMTEXT
);
					
ALTER TABLE VARIABLE_SET_LISTS 
ADD CONSTRAINT VSL_U_NAME UNIQUE (NAME);

ALTER TABLE VARIABLE_SET_LISTS 
ADD CONSTRAINT VSL_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);