CREATE TABLE METRIC_GROUP_TEMPLATES (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	NAME VARCHAR(500) NOT NULL, 
	UPPERCASE_NAME VARCHAR(500) NOT NULL, 
	VARIABLE_SET_LIST_ID INTEGER NOT NULL, 
	METRIC_GROUP_NAME_VARIABLE VARCHAR(500) NOT NULL, 
	DESCRIPTION_VARIABLE MEDIUMTEXT,
	MATCH_REGEXES_VARIABLE MEDIUMTEXT,  
	BLACKLIST_REGEXES_VARIABLE MEDIUMTEXT,  
	TAGS_VARIABLE MEDIUMTEXT,  
	IS_MARKED_FOR_DELETE BOOLEAN NOT NULL
);

ALTER TABLE METRIC_GROUP_TEMPLATES 
ADD CONSTRAINT MGTP_U_NAME UNIQUE (NAME);

ALTER TABLE METRIC_GROUP_TEMPLATES 
ADD CONSTRAINT MGTP_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);

ALTER TABLE METRIC_GROUP_TEMPLATES 
ADD CONSTRAINT MGTP_VSL_FK FOREIGN KEY (VARIABLE_SET_LIST_ID) REFERENCES VARIABLE_SET_LISTS(ID);