CREATE TABLE NOTIFICATION_GROUP_TEMPLATES (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	NAME VARCHAR(500) NOT NULL, 
	UPPERCASE_NAME VARCHAR(500) NOT NULL, 
	VARIABLE_SET_LIST_ID INTEGER NOT NULL, 
	NOTIFICATION_GROUP_NAME_VARIABLE VARCHAR(500) NOT NULL, 
	EMAIL_ADDRESSES_VARIABLE VARCHAR(500) NOT NULL,
	PAGERDUTY_SERVICE_NAME_VARIABLE VARCHAR(500) NOT NULL,  
	IS_MARKED_FOR_DELETE BOOLEAN NOT NULL
);

ALTER TABLE NOTIFICATION_GROUP_TEMPLATES 
ADD CONSTRAINT NGTP_U_NAME UNIQUE (NAME);

ALTER TABLE NOTIFICATION_GROUP_TEMPLATES 
ADD CONSTRAINT NGTP_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);

ALTER TABLE NOTIFICATION_GROUP_TEMPLATES 
ADD CONSTRAINT NGTP_VSL_FK FOREIGN KEY (VARIABLE_SET_LIST_ID) REFERENCES VARIABLE_SET_LISTS(ID);