CREATE TABLE METRIC_LAST_SEEN ( 
	METRIC_KEY_SHA1 VARCHAR(50) NOT NULL,  
	METRIC_KEY MEDIUMTEXT NOT NULL,  
	LAST_MODIFIED TIMESTAMP NULL DEFAULT NULL 
);

ALTER TABLE METRIC_LAST_SEEN 
ADD CONSTRAINT MLS_PK PRIMARY KEY (METRIC_KEY_SHA1);