ALTER TABLE NOTIFICATION_GROUPS ADD COLUMN NOTIFICATION_GROUP_TEMPLATE_ID INTEGER;
ALTER TABLE NOTIFICATION_GROUPS ADD COLUMN VARIABLE_SET_ID INTEGER;

ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_MGTPID_FK FOREIGN KEY (NOTIFICATION_GROUP_TEMPLATE_ID) REFERENCES NOTIFICATION_GROUP_TEMPLATES(ID);

ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_VSID_FK FOREIGN KEY (VARIABLE_SET_ID) REFERENCES VARIABLE_SETS(ID);

