CREATE TABLE METRIC_GROUP_REGEXES ( 
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	METRIC_GROUP_ID INTEGER NOT NULL, 
	IS_BLACKLIST_REGEX BOOLEAN NOT NULL, 
	PATTERN TEXT NOT NULL 
);

ALTER TABLE METRIC_GROUP_REGEXES 
ADD CONSTRAINT MGR_MGID_FK FOREIGN KEY (METRIC_GROUP_ID) REFERENCES METRIC_GROUPS(ID);