CREATE TABLE METRIC_GROUP_TAGS ( 
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	METRIC_GROUP_ID INTEGER NOT NULL, 
	TAG TEXT NOT NULL 
);

ALTER TABLE METRIC_GROUP_TAGS 
ADD CONSTRAINT MGT_MGID_FK FOREIGN KEY (METRIC_GROUP_ID) REFERENCES METRIC_GROUPS(ID);