CREATE TABLE NOTIFICATION_GROUPS ( 
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	NAME VARCHAR(500) NOT NULL,  
	UPPERCASE_NAME VARCHAR(500) NOT NULL,  
	EMAIL_ADDRESSES TEXT NOT NULL 
);
					
ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_U_NAME UNIQUE (NAME);

ALTER TABLE NOTIFICATION_GROUPS 
ADD CONSTRAINT NG_U_UPPERCASE_NAME UNIQUE (UPPERCASE_NAME);