CREATE TABLE OUTPUT_BLACKLIST (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,  
	METRIC_GROUP_ID INTEGER
);

ALTER TABLE OUTPUT_BLACKLIST 
ADD CONSTRAINT OB_MGID_FK FOREIGN KEY (METRIC_GROUP_ID) REFERENCES METRIC_GROUPS(ID);